import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";
import { cookies } from 'next/headers';


interface ListItem {
  id: number;
  title: string;
  description: string;
}

const poppins = Poppins({
  subsets: ['latin'],
  weight:"400",
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const token = cookieStore.get('access')?.value
  let initialLists: ListItem[] = []

  async function fetchUserLists(token: string): Promise<ListItem[]> {
    try {
      const response = await fetch('https://affiliatemarketing-production.up.railway.app/backend/api/v1/lists/', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${token}`,
        },
        cache: 'no-store',
      });

      if (!response.ok) {
        console.error(`Response status: ${response.status} ${response.statusText}`);
        throw new Error('Failed to fetch the lists');
      }

      const data = await response.json();
      // console.log('Fetched data:', data);
      return data;

    } catch (error) {
      console.error('Error Fetching the User Lists : ', error);
      throw error;
    }
  }

  if (token) {
    try {
      initialLists = await fetchUserLists(token)
    } catch (error) {
      console.error('Error fetching initial lists : ', error)
    }
  }
  const imageDirectURL = `${process.env.SITE_URL}/images/logo.png`;
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" crossOrigin="use-credentials" />
        <meta name="subject" content="OuraGen" />
        <meta
          name="description"
          content="Discover the ultimate ease in the shopping via various platforms through a single interface."
        />
        <meta
          name="keywords"
          content="Ecommerce, List, Notes, Shopping, buy online, online shopping, best online store, discount deals, free shipping, shop now, buy [product name] online, best [product category] store, affordable [product name], luxury [product category], handmade [product name], best deals on [product name], [product name] near me, buy [product] with discount, fast delivery [product name], cheap [product name] online, black friday sale [product], christmas gifts for [audience], summer fashion trends, cyber monday deals, best [product] reviews, [brand] vs [brand] comparison, top-rated [product], customer reviews for [product], buy [product] in [city], best [product] store near me, online shopping in [location], how to choose the best [product], [product] buying guide, benefits of using [product], trending [product category]
          "
        />
        <meta name="language" content="en" />
        <meta name="url" content={process.env.SITE_URL} />
        <meta name="coverage" content="Worldwide" />
        <meta name="distribution" content="Global" />
        <meta name="target" content="all" />
        <meta name="rating" content="General" />
        <meta name="og:country-name" content="India" />
        <meta name="og:region" content="India" />
        <meta property="og:url" content={process.env.SITE_URL} />
        <meta
          name="og:site_name"
          content="OuraGen"
        />
        <meta property="og:type" content="Website" />
        <meta
          property="og:title"
          content="OuraGen"
        />
        <meta
          property="og:description"
          content="Discover the ultimate ease in the shopping via various platforms through a single interface."
        />
        <meta name="twitter:card" content="website" />
        <meta
          name="twitter:site"
          content="OuraGen"
        />
        <meta
          name="twitter:title"
          content="OuraGen"
        />
        <meta
          name="twitter:description"
          content="Discover the ultimate ease in the shopping via various platforms through a single interface."
        />
        <meta itemProp="name" content="OuraGen" />
        <meta
          itemProp="description"
          content="Discover the ultimate ease in the shopping via various platforms through a single interface."
        />
        <meta name="author" content="BGV Shiva" />

        <meta property="og:image" content={imageDirectURL} />
        <meta name="twitter:image" content={imageDirectURL} />

        <link rel="shortcut icon" href="favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="150x150"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        /><meta name='impact-site-verification' value='8255de2a-28d6-413d-9513-268ea5ec52a2' />#impact.com
          (function(i,m,p,a,c,t){c.ire_o=p;c[p]=c[p]||function(){(c[p].a=c[p].a||[]).push(arguments)};t=a.createElement(m);var z=a.getElementsByTagName(m)[0];t.async=1;t.src=i;z.parentNode.insertBefore(t,z)})('https://utt.impactcdn.com/P-A6096136-034b-4566-9f49-8fac6d2594021.js','script','impactStat',document,window);impactStat('transformLinks');impactStat('trackImpression');
      </head>
      <body className={`${poppins.className}`}>
        <Navbar token={token} initialLists={initialLists} />
        {children}
      </body>
    </html>
  );
}
