# Generated by Django 4.2.6 on 2024-09-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
