# Generated by Django 4.2.6 on 2024-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinks',
            name='product_price',
            field=models.CharField(default='100', max_length=50),
        ),
    ]
