# Generated by Django 4.2.6 on 2024-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_productlinks_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listAuthor', models.CharField(max_length=75000)),
                ('listTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('listContent', models.TextField()),
            ],
        ),
    ]
