# Generated by Django 4.2.6 on 2024-10-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='UserLists',
        ),
    ]
