# Generated by Django 4.2.6 on 2024-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userlists_listauthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlists',
            old_name='listTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userlists',
            old_name='listAuthor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userlists',
            name='listContent',
        ),
        migrations.AddField(
            model_name='userlists',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
