# Generated by Django 5.1.2 on 2025-01-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_listtitle_userlists_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinks',
            name='product_category',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='productlinks',
            name='product_country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='productlinks',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productlinks',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productlinks',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
