# Generated by Django 5.1.2 on 2025-01-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_productlinks_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinks',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
    ]
