# Generated by Django 5.1.2 on 2025-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_productlinks_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinks',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
