# Generated by Django 5.1.2 on 2025-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlists',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlists',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
