/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dsjTRNk7XgP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Inter } from 'next/font/google'
import { useState , useEffect } from "react";

import Link from "next/link";

import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"

export function Navbar() {

  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if(window.scrollY > 0){
        setIsScrolled(true);
      }else{
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    handleScroll();
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  useEffect(() => {
    console.log("isScrolled updated:", isScrolled);
  }, [isScrolled]);

  return (
      <header
      className={`fixed top-0 left-0 z-50 w-full shadow-md mb-[0px] transition-colors duration-300 ${
        isScrolled ? 'bg-[#0bc772]' : 'bg-background'
      }`}
      >
        <div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="/" className="flex items-center gap-2 text-muted-foreground hover:text-foreground">
            <MountainIcon className={`h-6 w-6 ${
              isScrolled ? 'text-[white]' : 'text-[]'
            }`} />
            <span className={`text-lg font-semibold ${
              isScrolled ? 'text-[white]' : 'text-[]'
            }`}>Aone</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link
              href="/list"
              className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
            >
              <ListIcon className={`h-5 w-5 ${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`} /> 
              <span className={`${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`}>List</span>
            </Link>
            <Link
              href="/shop"
              className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
            >
              <ShoppingCartIcon className={`h-5 w-5 ${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`} /> 
              <span className={`${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`}>Shop</span>
            </Link>
            <Link
              href="/products"
              className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
            >
              <PackageIcon className={`h-5 w-5 ${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`} /> 
              <span className={`${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`}>Products</span>
            </Link>
            <Link
              href="/profile"
              className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
            >
              <UserIcon className={`h-5 w-5 ${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`} /> 
              <span className={`${
                isScrolled ? 'text-[white]' : 'text-[]'
              }`}>Profile</span>
            </Link>
          </nav>
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="outline" size="icon" className="md:hidden">
                <MenuIcon className="h-6 w-6" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="md:hidden bg-[#0bc772]">
              <div className="flex flex-col items-start gap-4 p-6">
                <Link href="/" className="flex items-center gap-2 text-lg font-semibold">
                  <MountainIcon className="h-6 w-6 text-[white]" />
                  <span className='text-[white]'>Aone</span>
                </Link>
                <nav className="grid gap-2">
                  <Link
                    href="/list"
                    className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
                  >
                    <ListIcon className="h-5 w-5 text-[white]" />
                    <span className='text-[white]'>List</span>
                  </Link>
                  <Link
                    href="/shop"
                    className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
                  >
                    <ShoppingCartIcon className="h-5 w-5 text-[white]" />
                    <span className='text-[white]'>Shop</span>
                  </Link>
                  <Link
                    href="/products"
                    className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
                  >
                    <PackageIcon className="h-5 w-5 text-[white]" />
                    <span className='text-[white]'>Products</span>
                  </Link>
                  <Link
                    href="/profile"
                    className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
                  >
                    <UserIcon className="h-5 w-5 text-[white]" />
                    <span className='text-[white]'>Profile</span>
                  </Link>
                </nav>
              </div>
            </SheetContent>
          </Sheet>
        </div>
      </header>
  )
}

function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PackageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
